services:
  fideslang:
    image: ethyca/fideslang:local
    command: /bin/bash
    volumes:
      - type: bind
        source: .
        target: /fideslang
        read_only: False

  docs:
    build:
      context: docs/fides/
    volumes:
      - ./docs/fides:/docs
      - ./:/fides
    expose:
      - 8000
    ports:
      - "8000:8000"
