# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.4.3.dev2+gf6c1426.d20230623'
__version_tuple__ = version_tuple = (1, 4, 3, 'dev2', 'gf6c1426.d20230623')
