name: PR Checks

on:
  pull_request:
    branches:
      - main

env:
  CONTAINER: fideslang-local
  IMAGE: ethyca/fideslang:local

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build fideslang container
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: prod
          outputs: type=docker,dest=/tmp/${{ env.CONTAINER }}.tar
          push: false
          tags: ${{ env.IMAGE }}

      - name: Upload fideslang container
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/${{ env.CONTAINER }}.tar
          retention-days: 1

  Black:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fideslang container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fideslang image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run formatter
        run: make black

  Export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "pip"

      - name: Install Package
        run: pip install .

      - name: Run Export
        run: python scripts/export_default_taxonomy.py

  Pylint:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fideslang container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fideslang image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        run: make pylint

  Mypy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fideslang container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fideslang image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run typechecker
        run: make mypy

  Xenon:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fideslang container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fideslang image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run cyclomatic complexity check
        run: make xenon

  Pytest:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download fideslang container
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.CONTAINER }}
          path: /tmp/

      - name: Load fideslang image
        run: docker load --input /tmp/${{ env.CONTAINER }}.tar

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit test suite
        run: make pytest
