name: Publish updated docs to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - "mkdocs/**"
  
jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r mkdocs/requirements.txt
      - name: Publish docs
        run: mkdocs gh-deploy -v -f mkdocs/mkdocs.yml --force
        