name: Publish fideslang

on:
  push:
    tags:
      - "*"

jobs:
  upload_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Twine
        run: pip install twine

      - name: Build Distributions
        run: |
          python -m pip install build
          python -m build

      - name: Twine Upload
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
